AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HoushinSeiyuWikipedia:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      Events:
        GetSeiyu:
          Type: Api
          Properties:
            Path: /
            Method: get
