# docker-compose.yml
version: "3.1"

services:

  wordpress:
    image: wordpress
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    environment:
       WORDPRESS_DB_PASSWORD: wppass

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wppass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpres
    ports:
      - 3333:3306
