version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
